### ISSUE TITLE
Scaling does not work

### ISSUE THREAD

**Issue by truckerboy** [mmtrt/acrordrdc#13]
scaling does not work on this snap on Ubuntu 20.04. 
"--force-device-scale-factor" does not work when added to the command within the .desktop file. Any ideas on how to make scaling work? I can barely read the Adobe Acrobat font on my 4K monitor. Please help. All other apps scale beautifully. I am assuming this has something to do with wine but not sure.

**Comment by mmtrt** [comment]
Run this command then goto `graphics` tab set screen `dpi` 

`acrordrdc winecfg`

**Comment by truckerboy** [comment]
That worked, thank you very much.

**Comment by towadroid** [comment]
Just leaving a comment for future users: I had to run `acrordrdc.wine winecfg`
