### ISSUE TITLE
acrordrdc does't provide .desktop file, can't select it to open PDF files from Nautilus

### ISSUE THREAD

**Issue by jdpipe** [mmtrt/acrordrdc#31]
This is a wonderful snap, make it very easy to get Adobe Reader working in Ubuntu.

I note that I had problems with running it the second time, for which the following was helpful:
https://linuxconfig.org/how-to-install-adobe-acrobat-reader-dc-wine-on-ubuntu-20-04-focal-fossa-linux

However, I wanted to note that I cannot associate acrordrdc with .pdf files because this snap does not include a .desktop file. Having this would improve usability, since one could right-click a PDF and select to open it with acrordrdc instead of default Evince.

Not sure how Snaps handle the installation/use of .desktop files. This seems to be relevant though:
https://snapcraft.io/docs/desktop-menu-icon-support

**Comment by DefaultX-od** [comment]
A quick workaround for you would be to put `%U` at the end of the command, just like on a screenshot below:

![Снимок экрана от 2022-12-27 07-31-16](https://user-images.githubusercontent.com/61311905/209611523-13e283d9-2018-4426-ac0a-bec92d4cddd1.png)

To do that, you can use menulibre.
