### ISSUE TITLE
Support for arm64 architecture ?

### ISSUE THREAD

**Issue by glykos** [mmtrt/acrordrdc#43]
Thank you for your work, I'm using your acrordrdc snap on all my linux machines mainly to sign PDF files. I am currently setting-up a raspberry Pi 5 as a not-so-stupid terminal. `snapd` installs without issues, and `snap list` reports the following (Pi5 is based on debian bookworm) : 

```
Name               Version           Rev    Tracking       Publisher   Notes
bare               1.0               5      latest/stable  canonical✓  base
core               16-2.61.1         16578  latest/stable  canonical✓  core
core22             20240111          1125   latest/stable  canonical✓  base
gnome-42-2204      0+git.ff35a85     143    latest/stable  canonical✓  -
gtk-common-themes  0.1-81-g442e511   1535   latest/stable  canonical✓  -
snap-store         41.3-71-g709398e  963    latest/stable  canonical✓  -
```
The question is : is there any chance that the `acrordrdc` snap could possibly support this architecture ?

Again, thank you for this snap.

**Comment by mmtrt** [comment]
yes it is possible using `box86` or `box64` but currently snap store does not allow upload of snaps that are using `all` arch with having only x86, x64 linux deps for wine and runtime snaps it is only blocker atm for arm64 wine app snap.
