### ISSUE TITLE
wine version outdated , fonts missing

### ISSUE THREAD

**Issue by takov751** [mmtrt/acrordrdc#5]
This is almost duplicate of #3 .
There are some workarounds for this solution.
Workarounds

For the signature it's possible use an image of the signature and then just use the stamp tool to paste it. Not the most secure option but it's a choice

Dialogues and preference screens without text can be fixed by installing microsoft fonts, especially the sego* fonts.

https://appdb.winehq.org/objectManager.php?sClass=version&iId=32266

**Comment by mmtrt** [comment]
can you retest snap install from edge see if these changes fix issues?

make sure its fresh install I could test it but I have limited data.

`snap install --edge acrordrdc`

**Comment by takov751** [comment]
I tested it . With the wine 5.0 works pretty well,however fonts still missing. Only solution is to change back to winxp. I think the problem is we can't solve, that for some reason the reader want to use a weird font :expressionless: devastating. Thank you for the quick change. With the change from win7 to winxp and disable protection mode its works flawlessly. Thank your your hard work :+1:
