### ISSUE TITLE
Fonts are missing

### ISSUE THREAD

**Issue by EagleScreen** [mmtrt/acrordrdc#8]
Font of the dialogs and buttons are missing. I can reproduce this issue in Linux Mint 19.3, Debian 10.3 and OpenSuse Leap 15.2 beta.
![Captura de pantalla de 2020-04-08 10-25-55](https://user-images.githubusercontent.com/2446961/78774166-94652a00-7994-11ea-84ce-0afcd36c570c.png)

**Comment by mmtrt** [comment]
Duplicate issue please read #3 #5 though this app depends on `Segoe UI` which is proprietary and due to copyright issues I can't ship this font with snap.

**Comment by EagleScreen** [comment]
> Duplicate issue please read #3 #5 though this app depends on `Segoe UI` which is proprietary and due to copyright issues I can't ship this font with snap.

The issue result fixed changing in winecfg Windows version from Windows 7 to Windows XP. Why do not you apply that fix in your snap package configuration?

**Comment by mmtrt** [comment]
> > Duplicate issue please read #3 #5 though this app depends on `Segoe UI` which is proprietary and due to copyright issues I can't ship this font with snap.
> 
> The issue result fixed changing in winecfg Windows version from Windows 7 to Windows XP. Why do not you apply that fix in your snap package configuration?

done please test

`snap install --edge acrordrdc`

**Comment by EagleScreen** [comment]
now in the same computer i am having this issue:
rafael@lenovo:~> echo $SHELL
/bin/bash
rafael@lenovo:~> snap install --edge acrordrdc
acrordrdc (edge) 2018.011.20063 from Taqi Raza (mmtrt) installed
rafael@lenovo:~> acrordrdc
000b:err:winediag:nodrv_CreateWindow Application tried to create a window,
but no driver could be loaded.
000b:err:winediag:nodrv_CreateWindow The explorer process failed to start.
0010:err:winediag:nodrv_CreateWindow Application tried to create a window,
but no driver could be loaded.
0010:err:winediag:nodrv_CreateWindow The explorer process failed to start.
wine: configuration in L"/home/rafael/snap/acrordrdc/common/.wine" has been
updated.
Using winetricks 20191224-next - sha256sum:
472eba29dbf056c87afd39a70426886064040e0bc2c3b63c17baf469b0bf2be2 with
wine-5.0 and WINEARCH=win32
Executing w_do_call mspatcha
Executing load_mspatcha
Executing mkdir -p
/home/rafael/snap/acrordrdc/common/.cache/winetricks/win2ksp4
Executing cd /home/rafael/snap/acrordrdc/common/.cache/winetricks/win2ksp4
Downloading
https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
to /home/rafael/snap/acrordrdc/common/.cache/winetricks/win2ksp4
--2020-04-08 20:31:57--
https://ftp.gnome.org/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
Resolving ftp.gnome.org (ftp.gnome.org)... 194.71.11.173, 194.71.11.165,
2001:6b0:19::173, ...
Connecting to ftp.gnome.org (ftp.gnome.org)|194.71.11.173|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location:
https://saimei.ftp.acc.umu.se/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
[following]
--2020-04-08 20:31:57--
https://saimei.ftp.acc.umu.se/mirror/archive/ftp.sunet.se/pub/security/vendor/microsoft/win2000/Service_Packs/usa/W2KSP4_EN.EXE
Resolving saimei.ftp.acc.umu.se (saimei.ftp.acc.umu.se)... 194.71.11.138,
2001:6b0:19::138
Connecting to saimei.ftp.acc.umu.se
(saimei.ftp.acc.umu.se)|194.71.11.138|:443...
connected.
HTTP request sent, awaiting response... 200 OK
Length: 135477136 (129M) [application/x-msdownload]
Saving to: ‘W2KSP4_EN.EXE’

W2KSP4_EN.EXE
100%[===============================================================================>]
129,20M  3,77MB/s    in 37s

2020-04-08 20:32:35 (3,47 MB/s) - ‘W2KSP4_EN.EXE’ saved
[135477136/135477136]

Executing cd /home/rafael
Executing cabextract -q -d
/home/rafael/snap/acrordrdc/common/.wine/dosdevices/c:/windows/temp -L -F
i386/mspatcha.dl_
/home/rafael/snap/acrordrdc/common/.cache/winetricks/win2ksp4/W2KSP4_EN.EXE
Executing cabextract -q
--directory=/home/rafael/snap/acrordrdc/common/.wine/dosdevices/c:/windows/system32
/home/rafael/snap/acrordrdc/common/.wine/dosdevices/c:/windows/temp/i386/mspatcha.dl_
Using native,builtin override for following DLLs: mspatcha
Executing wine regedit /S C:\windows\Temp\override-dll.reg
Executing w_do_call winxp
Executing load_winxp
Setting Windows version to winxp
Executing wine regedit /S C:\windows\Temp\set-winver.reg
------------------------------------------------------
Running /snap/acrordrdc/12/wine-platform/wine-stable/bin/wineserver -w.
This will hang until all wine processes in
prefix=/home/rafael/snap/acrordrdc/common/.wine terminate
------------------------------------------------------
Gtk-Message: 20:32:50.584: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:32:50.586: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:36:17.887: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:36:17.890: Failed to load module "canberra-gtk-module"
002d:err:msi:ITERATE_Actions Execution halted, action L"LaunchConditions"
returned 1603
--2020-04-08 20:37:14--
https://gist.github.com/mmtrt/896cf131e3956b23e8e47a5a52f58b01/raw/097cbd0eeb836d69a84423aaef9a7ead2840a111/acrordr
Resolving gist.github.com (gist.github.com)... 140.82.112.19
Connecting to gist.github.com (gist.github.com)|140.82.112.19|:443...
connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location:
https://gist.githubusercontent.com/mmtrt/896cf131e3956b23e8e47a5a52f58b01/raw/097cbd0eeb836d69a84423aaef9a7ead2840a111/acrordr
[following]
--2020-04-08 20:37:16--
https://gist.githubusercontent.com/mmtrt/896cf131e3956b23e8e47a5a52f58b01/raw/097cbd0eeb836d69a84423aaef9a7ead2840a111/acrordr
Resolving gist.githubusercontent.com (gist.githubusercontent.com)...
151.101.132.133
Connecting to gist.githubusercontent.com
(gist.githubusercontent.com)|151.101.132.133|:443...
connected.
HTTP request sent, awaiting response... 200 OK
Length: 943 [text/plain]
Saving to: ‘/tmp/acrordr’

acrordr
100%[===============================================================================>]
    943  --.-KB/s    in 0s

2020-04-08 20:37:16 (6,45 MB/s) - ‘/tmp/acrordr’ saved [943/943]

mv: cannot stat '/home/rafael/snap/acrordrdc/common/.wine/drive_c/Program
Files/Adobe/Acrobat Reader DC/Reader/AcroCEF/RdrCEF.exe': No such file or
directory
wine: cannot find '/home/rafael/snap/acrordrdc/common/.wine/drive_c/Program
Files/Adobe/Acrobat Reader DC/Reader/AcroRd32.exe'
rafael@lenovo:~>

**Comment by mmtrt** [comment]
can you test again thanks.

`snap install --edge acrordrdc`

**Comment by EagleScreen** [comment]
I obtained that error in the screenshot during installation, but after all,
app launches and runs, and now i can see the fonts in the buttons.

**Comment by EagleScreen** [comment]
Hi, current version in edge is working for me and with fonts in official Ubuntu 20.04.

**Comment by alexanderadam** [comment]
I don't seem to have this issue in the current stable build.
Should `Segoe UI` be available if I have the font in the `~/.fonts/` directory on the host system?

@mmtrt you are a genious! Thank you so much for creating all these Wine Snaps! :pray:

**Comment by mmtrt** [comment]
Yes it can load local fonts stored in `~/.fonts`

Currently I don't have planned new snaps still have to migrate my other wine snaps to new script which needs changing though I'm just busy with IRL things also getting married next month.

**Comment by alexanderadam** [comment]
> Currently I don't have planned new snaps still have to migrate my other wine snaps to new script which needs changing

No worries! Always remember that your private life and your health are coming first! So don't let your projects (or their users) put pressure on you! :wink: 

> also getting married next month.

Awesome, congratulations! :tada: :bride_with_veil: :man_in_tuxedo:

**Comment by mmtrt** [comment]
Thank you ❤️
